[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/inhouse"
  to = "/inhouse.html"
  status = 200

[[redirects]]
  from = "/events"
  to = "/events.html"
  status = 200

[[redirects]]
  from = "/gangs"
  to = "/gangs.html"
  status = 200
